[project]
name = "flinkprocessing"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "apache-flink>=2.2.0",
    "confluent-kafka>=2.13.0",
    "faker>=40.5.1",
]
